name: location_example
description: Demonstrates how to use the location plugin.

dependencies:
  flutter:
    sdk: flutter
  location:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1

flutter:
  uses-material-design: true
